'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class IONew

    '''<summary>
    '''lblmsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblmsg As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''vsIO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vsIO As Global.System.Web.UI.WebControls.ValidationSummary

    '''<summary>
    '''rfvClient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvClient As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''rfvContact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvContact As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''rfvSalesRep control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvSalesRep As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''rfvId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvId As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''rfvName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvName As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''rfvType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvType As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''rfvStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvStatus As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''rfvClick control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvClick As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''rfvQuanity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvQuanity As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''rfvAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvAmount As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''revAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revAmount As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''ddClient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddClient As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddContact control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddContact As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddSalesRep control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddSalesRep As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtIOId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIOId As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtIOName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIOName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddStatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtUnitCost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUnitCost As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtQuanity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQuanity As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAmount As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNote As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cmdAddIO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmdAddIO As Global.System.Web.UI.WebControls.Button
End Class
