'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class MyAdCampaignsPullReview

    '''<summary>
    '''form1 control.
    '''</summary>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''btnView control.
    '''</summary>
    Protected WithEvents btnView As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSubmit control.
    '''</summary>
    Protected WithEvents btnSubmit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''gridPreview control.
    '''</summary>
    Protected WithEvents gridPreview As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lblStatus control.
    '''</summary>
    Protected WithEvents lblStatus As Global.System.Web.UI.WebControls.Label

End Class 