'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class Portal_MyAdCampaigns

    '''<summary>
    '''btnPullApiCampaigns control.
    '''</summary>
    Protected WithEvents btnPullApiCampaigns As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''gridApiCampaigns control.
    '''</summary>
    Protected WithEvents gridApiCampaigns As Global.System.Web.UI.WebControls.GridView

End Class 