'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class Portal_ShortedCampaigns
    '''<summary>
    '''ddlClient control.
    '''</summary>
    Protected WithEvents ddlClient As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlMonth control.
    '''</summary>
    Protected WithEvents ddlMonth As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cmdGetReport control.
    '''</summary>
    Protected WithEvents cmdGetReport As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''cvError control.
    '''</summary>
    Protected WithEvents cvError As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''gridShortedCampaigns control.
    '''</summary>
    Protected WithEvents gridShortedCampaigns As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lblMessage control.
    '''</summary>
    Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label
End Class 