'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Partial Public Class Portal_TestPage

    '''<summary>
    '''btnGetCampaigns control.
    '''</summary>
    Protected WithEvents btnGetCampaigns As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblResult control.
    '''</summary>
    Protected WithEvents lblResult As Global.System.Web.UI.WebControls.Label

End Class 